baseURL = 'https://hugokatzer.tech/'
languageCode = 'en-us'
#title = 'Hugo Sokolowski-Katzer'
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[params]
  author = 'Hugo Katzer'
  description = 'Personal Site'
  ShowBreadCrumbs = true


[params.profileMode]
    enabled = true
    title = 'Hugo Sokolowski-Katzer'
    subtitle = 'MSc AI Student'
    imageUrl = 'img/hampter.jpg'
    imageTitle = 'Hugo Katzer'

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Blog'
  url = '/blog'
  weight = 2

[[menu.main]]
  name = 'Projects'
  url = '/projects'
  weight = 3

[[menu.main]]
  name = 'About me'
  url = '/about'
  weight = 4